set(OpenCV_DIR /home/lpj/Software/opencv34/share/OpenCV)
find_package(OpenCV REQUIRED CONFIG)
message(STATUS "Found OpenCV ${OpenCV_VERSION}")
message(STATUS "${OpenCV_INCLUDE_DIRS}, ${OpenCV_LIBRARIES}")
include_directories(${OpenCV_INCLUDE_DIRS})
link_directories(${OpenCV_LIBRARIES})

find_package(OpenMP REQUIRED)
#message(STATUS "Found OpenMP ${OpenMP_VERSION}")
#message(STATUS "${OpenMP_INCLUDE_DIRS}, ${OpenMP_LIBRARIES}")
#include_directories(${OpenMP_INCLUDE_DIRS})
#link_directories(${OpenMP_LIBRARIES})
